<?php

/**
 * @file
 * The ionic drupal api server module.
 *
 * This module creates a default Flag and associated views. The content is
 * intended to be an example and may be deleted afterward.
 */

/**
 * Remove any information that the module sets.
 *
 * @see hook_install()
 * @see hook_schema()
 * @see hook_modules_uninstalled()
 */
function ionic_drupal_api_server_uninstall() {
  // Remove the styles directory and generated images.
  \Drupal::configFactory()->getEditable('views.view.ionic_server_api')->delete();

}